#!/usr/bin/env bash
# Define function to check DNS record for a subdomain
function check_dns_record {
    subdomain=$1
    domain=$2
    record_type=$3
    destination=$(dig +short $subdomain.$domain $record_type)
    if [ -z "$destination" ]; then
        echo "No $record_type record found for $subdomain.$domain"
    else
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

# Check DNS records for subdomains
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    check_dns_record www $domain A
    check_dns_record lb-01 $domain A
    check_dns_record web-01 $domain A
    check_dns_record web-02 $domain A
else
    check_dns_record $subdomain $domain A
fi
