#!/usr/bin/env bash
# Transfer a file from a client to a server

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

echo "Transferring file $FILE to server at $IP..."

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME"@"$IP":~

echo "File transfer complete."