#!/usr/bin/env bash
# Configure nginx to redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4
# Update packages and install nginx
sudo apt-get update
sudo apt-get install -y nginx

new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "5i $new_string" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
