#!/usr/bin/env bash
# Configure a new Nginx server to have a custom 404 page 
# The page should contain the string 'Ceci n'est pas une pag'

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "7i $new_string" /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
sudo service nginx reload