#!/usr/bin/env bash
# Update packages and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80 and return "Hello World!" at the root location
# Configure http header to contain hostname
sudo echo "server {
    listen 80;
    root /var/www/html;
    index index.html;
    add_header X-Served-By $hostname;
    }
" | sudo tee /etc/nginx/sites-available/default


#Restart nginx
sudo service nginx restart

sudo echo "Hello World!" | sudo tee /var/www/html/index.html