#!/usr/bin/env bash
# This script is displaying "Best school" with an additional "Hi" after the 9th iteration
count=1
while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count -eq 9 ];
		then
		echo "Hi"
		fi
	((count++))
done
