#!/usr/bin/env bash
# script to run the whoami  command under the user passed as a argument

# check if arguments not passed is one
if [ $#  -ne 1  ]; then
    echo "Usage: $0 <Username>"
    exit 1
fi

user=$1
sudo -u  $user whoami
