#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get install -y nginx

# Set nginx user
sudo sed -i '1i\user nginx;' /etc/nginx/nginx.conf

# Set nginx to listen on all active IPs on port 8080
sudo sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-enabled/default

# Restart nginx service
sudo service nginx restart
